### PR TITLE
Don't fail the build in strict mode for outdated maven plugin or SDK API

### LINKED ISSUE #283: Make version check optional
### Expected Behaviour
A version update of the plugin should only optionally fail the build in strictValidation mode. 

### Actual Behaviour
At a client of mine all builds failed when a new update of the plugin was released, this included release and hotfix build which we want to be reproducible. 

We configured the plugin with strictValidation mode, turning every warning into an error. We want to use strictValidation mode because we also want to check warnings by the plugin. However we don't the build to fail once a new version is available.

Is it possible to add an extra validator setting to specifically disable this functionality? Or some other solution so the build does not automatically fail when a new version is available.

### Reproduce Scenario (including but not limited to)
Configure the project 
```
<plugins>
      <plugin>
          <groupId>com.adobe.aem</groupId>
          <artifactId>aemanalyser-maven-plugin</artifactId>
          <version>1.5.12</version>
          <configuration>
               <strictValidation>true</strictValidation >
          </configuration>
          <executions>
                <execution>
                    <id>aem-analyser</id>
                    <goals>
                        <goal>project-analyse</goal>                           
                    </goals>
                </execution>
            </executions>
      </plugin>
</plugins>
```

#### Steps to Reproduce
n/a

#### Platform and Version
AEM 6.5 On Prem
Mac OS X
non latest version of the plugin

#### Sample Code that illustrates the problem
n/a

#### Logs taken while reproducing problem
n/a

### PR DESCRIPTION
**Pull request by cziegeler**
Provide new option to separately turn this on.

This fixes #283 

## Description

In addition to the analysers checking for "code" problems, the maven plugin contains an additional check to warn on an outdated version of the plugin or an outdated configured SDK API version. In "strict" mode, only the analysers should fail the build but not the latter checks.

Introduced a new configuration option strictVersionValidation to fail the build for those cases.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: aemanalyser-maven-plugin/src/main/java/com/adobe/aem/analyser/mojos/AbstractAnalyseMojo.java [hunk 1]
```diff
@@ -69,6 +69,14 @@ public abstract class AbstractAnalyseMojo extends AbstractAemMojo {
     @Parameter(defaultValue = "true", property = "failon.analyser.errors")
     private boolean failOnAnalyserErrors;
 
+    /**
+     * If enabled, warnings for maven plugin version or SDK API version are turned
+     * into errors and fail the build.
+     * @since 1.6.2
+     */
+    @Parameter(defaultValue = "false", property = "aem.analyser.strict.version")
+    protected boolean strictVersionValidation;
```
Comment (kwin) [inline aemanalyser-maven-plugin/src/main/java/com/adobe/aem/analyser/mojos/AbstractAnalyseMojo.java:78]: I think it makes sense to be able to configure the sensitivity of each analyzer (and the version check) individually.

Comment (cziegeler) [reply aemanalyser-maven-plugin/src/main/java/com/adobe/aem/analyser/mojos/AbstractAnalyseMojo.java:78]: Don't disagree - but I think this approach is ok for the version checks done by the plugin itself - these are not analyser checks and therefore are not executed in Cloud Service.
We can have a follow up issue about specific analysers. I think we also have a issue in Apache Sling open for this already.
